// <auto-generated />
using EFCore3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore3.Migrations
{
    [DbContext(typeof(DataContex))]
    [Migration("20231201065930_all Student add")]
    partial class allStudentadd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFCore3.Models.College", b =>
                {
                    b.Property<int>("CollegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CollegeAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CollegeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("CollegeId");

                    b.HasIndex("UniversityId");

                    b.ToTable("college");

                    b.HasData(
                        new
                        {
                            CollegeId = 1,
                            CollegeAddress = "123 College Street 1",
                            CollegeName = "Engineering College 1",
                            CollegeType = "Technical",
                            UniversityId = 1
                        },
                        new
                        {
                            CollegeId = 2,
                            CollegeAddress = "123 College Street 2",
                            CollegeName = "Engineering College 2",
                            CollegeType = "Technical",
                            UniversityId = 1
                        },
                        new
                        {
                            CollegeId = 3,
                            CollegeAddress = "123 College Street 3",
                            CollegeName = "Engineering College 3",
                            CollegeType = "Technical",
                            UniversityId = 2
                        },
                        new
                        {
                            CollegeId = 4,
                            CollegeAddress = "123 College Street 4",
                            CollegeName = "Engineering College 4",
                            CollegeType = "Technical",
                            UniversityId = 2
                        },
                        new
                        {
                            CollegeId = 5,
                            CollegeAddress = "123 College Street 5",
                            CollegeName = "Engineering College 5",
                            CollegeType = "Technical",
                            UniversityId = 3
                        },
                        new
                        {
                            CollegeId = 6,
                            CollegeAddress = "123 College Street 6",
                            CollegeName = "Engineering College 6",
                            CollegeType = "Technical",
                            UniversityId = 3
                        });
                });

            modelBuilder.Entity("EFCore3.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentHead")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NuumberOfClass")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.HasIndex("CollegeId");

                    b.ToTable("department");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CollegeId = 1,
                            DepartmentHead = "Prof. Muktesh",
                            DepartmentName = "Computer Science",
                            NuumberOfClass = 5
                        },
                        new
                        {
                            DepartmentId = 2,
                            CollegeId = 1,
                            DepartmentHead = "Prof. Resav",
                            DepartmentName = "Mech",
                            NuumberOfClass = 3
                        },
                        new
                        {
                            DepartmentId = 3,
                            CollegeId = 2,
                            DepartmentHead = "Prof. John",
                            DepartmentName = "ETC",
                            NuumberOfClass = 4
                        },
                        new
                        {
                            DepartmentId = 4,
                            CollegeId = 2,
                            DepartmentHead = "Prof. Rekha",
                            DepartmentName = "Civil",
                            NuumberOfClass = 5
                        },
                        new
                        {
                            DepartmentId = 5,
                            CollegeId = 3,
                            DepartmentHead = "Prof. Albert",
                            DepartmentName = "Computer Science",
                            NuumberOfClass = 5
                        },
                        new
                        {
                            DepartmentId = 6,
                            CollegeId = 3,
                            DepartmentHead = "Prof. Rohit",
                            DepartmentName = "Mech",
                            NuumberOfClass = 5
                        },
                        new
                        {
                            DepartmentId = 7,
                            CollegeId = 4,
                            DepartmentHead = "Prof. Jadu",
                            DepartmentName = "ETC",
                            NuumberOfClass = 5
                        },
                        new
                        {
                            DepartmentId = 8,
                            CollegeId = 4,
                            DepartmentHead = "Prof. Ramnesh",
                            DepartmentName = "Civil",
                            NuumberOfClass = 5
                        },
                        new
                        {
                            DepartmentId = 9,
                            CollegeId = 5,
                            DepartmentHead = "Prof. Rghav",
                            DepartmentName = "Computer Science",
                            NuumberOfClass = 5
                        },
                        new
                        {
                            DepartmentId = 10,
                            CollegeId = 6,
                            DepartmentHead = "Prof. Jignesh",
                            DepartmentName = "Computer Science",
                            NuumberOfClass = 5
                        });
                });

            modelBuilder.Entity("EFCore3.Models.Professor", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ProfessorAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfessorAge")
                        .HasColumnType("int");

                    b.Property<string>("ProfessorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Salary")
                        .HasColumnType("double");

                    b.HasKey("ProfessorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("professor");

                    b.HasData(
                        new
                        {
                            ProfessorId = 1,
                            DepartmentId = 1,
                            ProfessorAddress = "Muktanagar 1234",
                            ProfessorAge = 40,
                            ProfessorName = "Prof. Muktesh",
                            Salary = 50000.120000000003
                        },
                        new
                        {
                            ProfessorId = 2,
                            DepartmentId = 2,
                            ProfessorAddress = "Resavnagar 1234",
                            ProfessorAge = 34,
                            ProfessorName = "Prof. Resav",
                            Salary = 35000.120000000003
                        },
                        new
                        {
                            ProfessorId = 3,
                            DepartmentId = 3,
                            ProfessorAddress = "JohnNagar 1234",
                            ProfessorAge = 34,
                            ProfessorName = "Prof. John",
                            Salary = 15000.34
                        },
                        new
                        {
                            ProfessorId = 4,
                            DepartmentId = 4,
                            ProfessorAddress = "RekhaNagar 1234",
                            ProfessorAge = 29,
                            ProfessorName = "Prof. Rekha",
                            Salary = 25000.459999999999
                        },
                        new
                        {
                            ProfessorId = 5,
                            DepartmentId = 5,
                            ProfessorAddress = "AlbertNagar 1234",
                            ProfessorAge = 58,
                            ProfessorName = "Prof. Albert",
                            Salary = 60000.0
                        },
                        new
                        {
                            ProfessorId = 6,
                            DepartmentId = 6,
                            ProfessorAddress = "RohitNagar 1234",
                            ProfessorAge = 28,
                            ProfessorName = "Prof. Rohit",
                            Salary = 26000.0
                        },
                        new
                        {
                            ProfessorId = 7,
                            DepartmentId = 7,
                            ProfessorAddress = "JaduNagar 1234",
                            ProfessorAge = 38,
                            ProfessorName = "Prof. Jadu",
                            Salary = 58000.0
                        },
                        new
                        {
                            ProfessorId = 8,
                            DepartmentId = 8,
                            ProfessorAddress = "RamneshNagar 1234",
                            ProfessorAge = 34,
                            ProfessorName = "Prof. Ramnesh",
                            Salary = 38000.0
                        },
                        new
                        {
                            ProfessorId = 9,
                            DepartmentId = 9,
                            ProfessorAddress = "RghavNagar 1234",
                            ProfessorAge = 41,
                            ProfessorName = "Prof. Rghav",
                            Salary = 45000.0
                        },
                        new
                        {
                            ProfessorId = 10,
                            DepartmentId = 10,
                            ProfessorAddress = "JigneshNagar 1234",
                            ProfessorAge = 46,
                            ProfessorName = "Prof. Jignesh",
                            Salary = 55000.0
                        });
                });

            modelBuilder.Entity("EFCore3.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("StudentMarks")
                        .HasColumnType("double");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("StudentPercentage")
                        .HasColumnType("double");

                    b.Property<string>("StudentResult")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StudentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("student");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Age = 18,
                            DepartmentId = 1,
                            StudentAddress = "Prakash Nagar 2589",
                            StudentMarks = 980.0,
                            StudentName = "Prasad",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 2,
                            Age = 19,
                            DepartmentId = 1,
                            StudentAddress = "Prakash Nagar 2589",
                            StudentMarks = 680.0,
                            StudentName = "Aras",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 3,
                            Age = 16,
                            DepartmentId = 2,
                            StudentAddress = "Prakash Nagar 2589",
                            StudentMarks = 520.0,
                            StudentName = "Anubhab",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 4,
                            Age = 17,
                            DepartmentId = 2,
                            StudentAddress = "Prakash Nagar 2589",
                            StudentMarks = 750.0,
                            StudentName = "Pranab",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 5,
                            Age = 20,
                            DepartmentId = 3,
                            StudentAddress = "Some Address",
                            StudentMarks = 850.0,
                            StudentName = "Amit",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 6,
                            Age = 18,
                            DepartmentId = 3,
                            StudentAddress = "Another Address",
                            StudentMarks = 720.0,
                            StudentName = "Sara",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 7,
                            Age = 21,
                            DepartmentId = 4,
                            StudentAddress = "Yet Another Address",
                            StudentMarks = 920.0,
                            StudentName = "Rahul",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 8,
                            Age = 22,
                            DepartmentId = 4,
                            StudentAddress = "One More Address",
                            StudentMarks = 630.0,
                            StudentName = "Neha",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 9,
                            Age = 19,
                            DepartmentId = 5,
                            StudentAddress = "Sunset Avenue",
                            StudentMarks = 200.0,
                            StudentName = "Sandeep",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 10,
                            Age = 20,
                            DepartmentId = 5,
                            StudentAddress = "Maple Street",
                            StudentMarks = 720.0,
                            StudentName = "Monica",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 11,
                            Age = 18,
                            DepartmentId = 6,
                            StudentAddress = "Greenfield Road",
                            StudentMarks = 190.0,
                            StudentName = "Rajesh",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 12,
                            Age = 21,
                            DepartmentId = 6,
                            StudentAddress = "Cypress Lane",
                            StudentMarks = 670.0,
                            StudentName = "Pooja",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 13,
                            Age = 22,
                            DepartmentId = 7,
                            StudentAddress = "Oak Street",
                            StudentMarks = 950.0,
                            StudentName = "Vinay",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 14,
                            Age = 19,
                            DepartmentId = 7,
                            StudentAddress = "Cedar Avenue",
                            StudentMarks = 820.0,
                            StudentName = "Aisha",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 15,
                            Age = 20,
                            DepartmentId = 7,
                            StudentAddress = "Pine Road",
                            StudentMarks = 890.0,
                            StudentName = "Rakesh",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 16,
                            Age = 21,
                            DepartmentId = 8,
                            StudentAddress = "Birch Lane",
                            StudentMarks = 750.0,
                            StudentName = "Nina",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 17,
                            Age = 18,
                            DepartmentId = 8,
                            StudentAddress = "Redwood Boulevard",
                            StudentMarks = 910.0,
                            StudentName = "Kiran",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 18,
                            Age = 22,
                            DepartmentId = 9,
                            StudentAddress = "Fir Street",
                            StudentMarks = 680.0,
                            StudentName = "Aditi",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 19,
                            Age = 20,
                            DepartmentId = 9,
                            StudentAddress = "Willow Lane",
                            StudentMarks = 870.0,
                            StudentName = "Suman",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 20,
                            Age = 21,
                            DepartmentId = 9,
                            StudentAddress = "Magnolia Street",
                            StudentMarks = 720.0,
                            StudentName = "Vikas",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 21,
                            Age = 19,
                            DepartmentId = 10,
                            StudentAddress = "Cherry Avenue",
                            StudentMarks = 930.0,
                            StudentName = "Nisha",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        },
                        new
                        {
                            StudentId = 22,
                            Age = 22,
                            DepartmentId = 10,
                            StudentAddress = "Chestnut Road",
                            StudentMarks = 690.0,
                            StudentName = "Rohit",
                            StudentPercentage = 0.0,
                            StudentResult = ""
                        });
                });

            modelBuilder.Entity("EFCore3.Models.University", b =>
                {
                    b.Property<int>("UniversityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnversityAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnversityType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnvesrsityGrade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UniversityId");

                    b.ToTable("universitie");

                    b.HasData(
                        new
                        {
                            UniversityId = 1,
                            UniversityName = "Harvard University",
                            UnversityAddress = "Cambridge, Massachusetts",
                            UnversityType = "Private",
                            UnvesrsityGrade = "A+"
                        },
                        new
                        {
                            UniversityId = 2,
                            UniversityName = "MIT",
                            UnversityAddress = "Cambridge, Massachusetts",
                            UnversityType = "Private",
                            UnvesrsityGrade = "A"
                        },
                        new
                        {
                            UniversityId = 3,
                            UniversityName = "Stanford University",
                            UnversityAddress = "Stanford, California",
                            UnversityType = "Private",
                            UnvesrsityGrade = "A+"
                        });
                });

            modelBuilder.Entity("EFCore3.Models.College", b =>
                {
                    b.HasOne("EFCore3.Models.University", "University")
                        .WithMany("Colleges")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("EFCore3.Models.Department", b =>
                {
                    b.HasOne("EFCore3.Models.College", "College")
                        .WithMany("Departments")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("EFCore3.Models.Professor", b =>
                {
                    b.HasOne("EFCore3.Models.Department", "Department")
                        .WithMany("Professors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCore3.Models.Student", b =>
                {
                    b.HasOne("EFCore3.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCore3.Models.College", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("EFCore3.Models.Department", b =>
                {
                    b.Navigation("Professors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EFCore3.Models.University", b =>
                {
                    b.Navigation("Colleges");
                });
#pragma warning restore 612, 618
        }
    }
}
